spring:
  application:
    name: inventory-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_management
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true